# Generated by Django 3.0.3 on 2020-03-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('event_type', models.PositiveIntegerField(choices=[(1, 'practice'), (2, 'match'), (3, 'scrim'), (4, 'pugs')])),
            ],
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.PositiveIntegerField(choices=[(1, 'message'), (2, 'twitter'), (3, 'youtube')])),
                ('item_body', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRole',
            fields=[
                ('player_role', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_items', models.ManyToManyField(blank=True, to='team.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_name', models.CharField(max_length=50)),
                ('players', models.ManyToManyField(blank=True, to='team.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.PlayerRole', unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='roster_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_id', to='team.Roster', unique=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.PositiveSmallIntegerField(choices=[(1, 'scrim'), (2, 'match')])),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_id', to='team.Event', unique=True)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a_id', to='team.Roster', unique=True)),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b_id', to='team.Roster', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedItem', models.ManyToManyField(blank=True, to='team.FeedItem')),
            ],
        ),
    ]
