# Generated by Django 3.0.3 on 2020-03-05 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200305_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team.PlayerRole'),
        ),
        migrations.AlterField(
            model_name='player',
            name='roster_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roster_id', to='team.Roster'),
        ),
    ]
