# Generated by Django 3.0.3 on 2020-03-05 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20200305_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='roster_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_id', to='team.Roster'),
        ),
    ]
