# Generated by Django 3.0.3 on 2020-03-05 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20200305_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.PlayerRole'),
        ),
    ]
