# Generated by Django 3.0.3 on 2020-03-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20200305_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
    ]
